repos:
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest discover -v tests
        language: system
        pass_filenames: false

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
